- src/_locales/de/messages.json
some of the translations are not good. i checked all translations and made some modifications in case it was necessary.
> update of german translation

- src/_locales/nl/messages.json
I created Dutch translations for this extension. Maybe you want to include them?
> Added Dutch translations

- src/browser_action.css
- src/browser_action.js
Material design and animations, you got to love them, I added an animation to the Add button since clicking it twice will cause the Add popup to hide again.
> Added a rotate animation to the Add (+) button, causing it to show as a Close button (x)

- src/_locales/ru/messages.json
- src/_locales/uk/messages.json
> Update and rename src/_locales to src/_locales/uk/messages.json

- src/browser_action.js
This doesn't add any new config options, but it does omit "hidden" calendars from the dropdown on the Add dialog.
> Fixed #275

- src/_locales/no/messages.json
> Norwegian language translation

- src/_locales/my-mm
- Myanmar (Burmese) language support.
> added Myanmar(Burmese) language support.

- src/_locales/zh-TW/messages.json
Chinese (Traditional) *(zh-TW)* language file has been created.
> Add Chinese (Traditional) translations

- src/_locales/tr/messages.json
Turkish translations have been added
> Turkish translations added

- src/_locales/zh-TW/messages.json
Incorrect translations has been corrected.
> Correct Chinese (Traditional) Translations

- src/_locales/vi/messages.json
Hi there!
I'm Thanh, I've added Vietnamese translation for your extension. Some keywords should match the corresponding ones in Vietnamese version of Google Calendar so new user of extensions will be able to use easier.
If you needed support anything related to Vietnamese, feel free to contact me.
> Added Vietnamese translation

- src/_locales/pl/messages.json
just added new src/_locales/pl/messages.json for Polish locale (in UTF-8)
> Added polish locale messages

- src/_locales/ko/messages.json
hi @manastungare :)
i had a korean translation. plz check :)
> Add korean language

- src/_locales/cs/messages.json
Updated Czech translation after #372.
> Updated Czech translation.

- src/_locales/sr_RS/messages.json
Added Serbian language (Latin script).
> Added Serbian language.

- src/_locales/ca/messages.json
- src/_locales/es/messages.json
Hi. I translated your extension to catalan. Please, tell me if I left something in the process.
> catalan translation

- src/_locales/tr/messages.json
* updated missing fields from en locale
* translated new strings
> Turkish Translation

- src/_locales/se/messages.json
Complete initial translation to swedish locale.
> Translation to swedish

- src/_locales/he/nessages.json
Translate all the string from `src/_locale/en/messages.json` to Hebrew (in `he/messages.json`).
> Hebrew Translation.

- src/_locales/de/messages.json
Fixed a typo and some very literal translations from the English locale.
> Updated German Translation

- src/_locales/be/messages.json
* Localization for Belarusian language (`be`) is added.
* Minor fixes to Russian localization (`ru`) file.
> Belarusian localization

- src/_locales/en/messages.json
- src/background.js
- src/feeds.js
- src/manifest.json
- src/options.html
- src/options.js
Added option to show notification. It is possible to set the settings under the options page
Requested on #7 and #293
> Add notification alert

- src/_locales/da/messages.json
This pull request will add Danish (da) translation.
> Add Danish translation

- src/browser_action.js
Instead of populating #calendar-events by appending events individually,
accumulate contents into a detached div and then (after a 100ms delay) replace
browser action popup size getting clipped go away. The idea came from the
workarounds discussed in https://crbug.com/428044. Fixes #224.
> Add a 100ms delay before rendering events to work around Chrome layout bug

- src/_locales/hr/messages.json
Adds Croatian (Hrvatska) translation
> Croatian (hr) translation

- src/_locales/en/messages.json
- src/background.js
- src/context_menu.js
- src/options.html
- src/options.js
Added option to toggle context menu item for "Add to Google Calendar" #183
> Added option to toggle "Add to Google Calendar" item in context menu.

- src/feeds.js
Solves https://github.com/manastungare/google-calendar-crx/issues/459
> When first 14 days in calendar are empty, check 28, 42, etc. up to 100 days

- src/background.js
- src/feeds.js
Changed to moment.js to handle setting alarm events, and using feeds.events to setting notifications for the next 14 days.
> Change to moment.js for creating alarm for notification #517

- src/_locales/vi/messages.json
- Fixed some slightly incorrect translations
- Updated new translation strings
> Updated Vietnamese translation

- .travis.yml
In case there's interest
https://travis-ci.com/stephengroat/google-calendar-crx/jobs/184307283
> Travis Builds

- src/_locales/ja/messages.json
This pull request will add Japanese translations.
> Add Japanese (jp) translations
